name: Unit Tests

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        node:
          - 8
          - 10
          - 14

    runs-on: ubuntu-latest
    name: Node v${{ matrix.node }}

    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm test
